sveltejs/sites

- sites/kit.svelte.dev/src/routes/docs/index.svelte
- sites/kit.svelte.dev/src/routes/migrating/index.svelte
Still not going to be a really sensible way to make editing docs easy until the docs JSON API server is set up, but we'd probably be making this change anyway.
Also some bonus reformatting from Prettier.
edit: Also fixed the migrating page.
Closes #8.
> fix documentation edit links

- .github/workflows/docs-deploy-trigger.yml
Manual workflow can can be triggered to deploy the docs from a repo.
> chore: add deploy-docs workflow

- packages/site-kit/components/Docs.svelte
- sites/kit.svelte.dev/static/icons/link.svg
The title heading link SVG was not showing up on Kit docs, looks like file wasn't moved over to the project. Added missing image and tweaked styles to make it align correctly.
> Add missing link SVG and tweak styling

- packages/site-kit/components/PreloadingIndicator.svelte
- packages/site-kit/index.js
- sites/kit.svelte.dev/src/routes/$layout.svelte
Closes #26 by adding the loading indicator from the original Svelte site to the new kit.svelte.dev site. I added the <PreloadingIndicator /> component to the site-kit package in this repo.
**Preview**
> Add preloading indicator from Svelte site

- packages/site-kit/components/Nav.svelte
- sites/kit.svelte.dev/src/routes/$layout.svelte
Closes #28 and #33. The $layout now passes the current segment to the Nav component so that the active page is highlighted. I have also:
- Added a chevron to indicate the drop down menu
- Made minor styling tweaks to accommodate the menu
- Removed the `passive` event modifier to fix #33
**Mobile**
**Desktop**
> Highlight active page in nav, fix touch menu opening

- packages/site-kit/components/Nav.svelte
This PR makes the header visible when focus is inside it.
Before this change, if you tabbed back into the header while it was hidden, your focus would be lost. I updated the styles to show the header if the user has tabbed into it, while preserving the existing hide-on-scroll behavior.
Since some browsers [don't support](https://caniuse.com/css-focus-within) `:focus-within` (mainly old Edge), I inverted the current CSS selectors so that the header is shown by default and only hidden if the browser supports focus-within. Otherwise, browsers that don't support focus-within would throw out the whole rule, permanently hiding the header for those users.
> a11y: make header visible when focus within

- packages/site-kit/components/Docs.svelte
- sites/kit.svelte.dev/src/routes/faq/index.svelte
This PR fixes the offset anchors in the FAQ so that the heading linked to is not covered by the header. 
For example, [this link](https://kit.svelte.dev/faq#hmr) looks like this in production (the "How do I use HMR with SvelteKit?" is covered by the header)...
And like this with my changes applied...
The implementation was copied from the Docs component.
I also fixed the permalink focus styles in the FAQ.
> Fix offset anchor in FAQ

- packages/site-kit/components/Hero.svelte
Certain versions of Safari do not support `img` as a fallback for `picture`, so we need the png to be a `source` fallback as well.
In addition, MIME types are added to skip having to check it with the server.
> Fix `picture` tag fallback for Safari

- packages/site-kit/components/Docs.svelte
- packages/site-kit/components/Hero.svelte
- sites/kit.svelte.dev/src/routes/docs/index.svelte
- sites/kit.svelte.dev/src/routes/index.svelte
- sites/kit.svelte.dev/src/routes/migrating/index.svelte
Several pages on the SvelteKit site did not have an h1, resulting in an [axe a11y violation](https://dequeuniversity.com/rules/axe/4.1/page-has-heading-one). This PR adds those headings and makes them only visible to screen readers so the pages look the same.
Also, the use of an h3 in the Hero component resulted in an [invalid heading order](https://dequeuniversity.com/rules/axe/4.1/heading-order) violation. There didn't seem to be much benefit to this being a heading, so I changed it to a div and updated the styles so it looked the same.
> Add h1s and fix heading order

- packages/site-kit/base.css
> fix body not using correct font

- sites/kit.svelte.dev/src/routes/__layout.svelte
When navigating to any page deeper than 1 level.
How it should behave:
> Fixed relative path in assets reference

- packages/site-kit/components/docs/Main.svelte
right now the typographical hierarchy is all wrong
> make h1 bigger

- packages/site-kit/base.css
these styles are messing things up — if they need to be reinstated when we update svelte.dev to use this version of site-kit, we should do so more carefully
> remove css

- packages/site-kit/components/NavItem.svelte
This allows linking to endpoints and thereby solves the broken link to https://svelte.dev/chat from the header on svelte.dev.
(made a pr [here](https://github.com/sveltejs/site-kit/pull/47) but only later noticed that that package is abandoned in favour of this one)
> Set rel="external" on external NavItem

- sites/kit.svelte.dev/src/routes/__layout.svelte
`https://kit.svelte.dev/chat` results in 404
We either use `https://svelte.dev/chat` or `/chat` and have 2 links to remember to change.
> use svelte.dev/chat in kit instead of /chat

- packages/repl/src/lib/Input/ComponentSelector.svelte
https://github.com/sveltejs/svelte-repl/pull/186
I'm sure there was a good reason for this, but I've been unable to figure out what it was
> remove scrollIntoView

- packages/site-kit/components/Nav.svelte
This PR improves the keyboard and screen reader navigation experience in the mobile nav.
- Move button before the list of links. This way, when the nav is opened with the keyboard, the links are the next item in the focus order. Previously, they were before the button in the DOM and could be missed by screen reader and keyboard users.
-  Add `aria-expanded` attribute to convey the state of the button to screen readers when focused.
- Automatically close the nav when focus moves outside of it. Previously, focus would move further down the page, but the nav is still open so focus could be lost.
> Improve keyboard a11y for mobile nav

- sites/svelte.dev/src/routes/docs/index.svelte
replaced "https://github.com/sveltejs/kit/edit/master/site/content/docs/{section.file}" with "https://github.com/sveltejs/svelte/edit/master/site/content/docs/{section.file}"
> Fix 'edit docs' button linking to sveltejs/kit

- packages/repl/src/lib/CodeMirror.svelte
- packages/repl/src/lib/index.svelte
https://github.com/sveltejs/svelte-repl/pull/137, albeit with just the `setCursor` method (I felt it better not to add more API surface area; moving the cursor, rather than selecting a range, is probably more familiar behaviour)
> move cursor to error/warning location

- packages/site-kit/components/docs/Main.svelte
The permalinks on h3s and below did not have an accessible name since they didn't have any text content. This PR adds visually-hidden "permalink" text to each one, which aligns them with the site-kit Permalink component.
This resolves the 104 ["Links must have discernible text"](https://dequeuniversity.com/rules/axe/4.3/link-name) issues found via Axe DevTools.
> Give heading permalinks an accessible name

- packages/site-kit/code.css
The color contrast of the syntax highlighting in the code samples did not meet WCAG AA standards (4.5 for small text), which could make it hard to read for people with low vision. This PR updates the colors used to match that threshold. This reduces the count of [color contrast Axe violations](https://dequeuniversity.com/rules/axe/4.0/color-contrast) to 233 from 1493 instances.
Contrast changes (checked using https://contrast-ratio.com with #f6fafd background):
- code-comment: was 3.93, now 5.23
- code-function: was 4.01, now 4.5
- code-string: was 3.49, now 4.65
- code-number: was 2.84, now 4.89
- code-template-string: was 3.05, now 4.85
Before:
After: 
I made a similar PR against the old site repo (https://github.com/sveltejs/svelte/pull/5681), but it looks like those changes got lost …
> Improve color contrast of syntax highlighting

- packages/repl/src/lib/Input/ModuleEditor.svelte
- packages/repl/src/lib/Message.svelte
- packages/repl/src/lib/Output/Viewer.svelte
- packages/repl/src/lib/index.svelte
- packages/repl/src/lib/workers/bundler/index.js
WIP. This debounces messages (so you're not constantly distracted by syntax errors while you're mid-word), and the plan is to also debounce imports (so if you type `import x from 'some-package-name'` you don't end up fetching `so` and `some-` and `some-pac` etc from unpkg.
The goal is the same as #130, but bundling still happens immediately, which is nicer UX.
> debouncing

- sites/svelte.dev/src/routes/tutorial/[slug]/_TableOfContents.svelte
The tutorial arrows look fine when served locally but appears different in production.
This line should align them to the center.
> fix tutorial nav arrows position

- packages/repl/src/lib/workers/bundler/plugins/commonjs.js
it seems acorn hangs if you specify `ecmaVersion: 'latest'`. i have no idea why. anyway, this seems to fix issues like #206 and #205
> use ecmaVersion: 13

- sites/svelte.dev/src/routes/__error.svelte
- sites/svelte.dev/src/routes/apps/index.svelte
- sites/svelte.dev/src/routes/examples/[slug]/_TableOfContents.svelte
- sites/svelte.dev/src/routes/faq/_faqs.js
- sites/svelte.dev/src/routes/faq/index.svelte
- sites/svelte.dev/src/routes/index.svelte
- sites/svelte.dev/src/routes/repl/[id]/_components/AppControls/UserMenu.svelte
`<base` tag was removed in #227 which makes links without `/` behaves differently, related to #229
> ensure links are absolute

- db/setup.sql
see https://github.com/sveltejs/api.svelte.dev/pull/21
> add todo table

- package.json
- pnpm-lock.yaml
- sites/kit.svelte.dev/package.json
- sites/svelte.dev/package.json
This updates to the latest version of vite-imagetools, which updates to sharp 0.29, and removes the need for the pnpm override. 
Dependencies install for me locally with this on WSL, and we will see how the Vercel deployment preview behaves.
> [chore] remove pnpm sharp override

- sites/svelte.dev/src/routes/tutorial/[slug]/index.svelte
Changes the `twitter:description` and `Description` `meta` tags to use the same properties as those used in the `<title>` element just above it (which does work), to prevent them from showing as "undefined".
Fixes #259
PS. The PR has been created through the GitHub UI so the changes are not quite tested. But they seemed so straightforward that the PR (or at least the trace to the relevant file it has) might help?
> fix undefined meta tags content

- packages/site-kit/src/lib/docs/Main.svelte
Closes #246
Avoids #73 in a slightly different way, see https://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/#method-B
> fix: h4s in docs overlay preceding text

- sites/svelte.dev/src/routes/tutorial/[slug]/index.svelte
"Next" button and its icon aren't vertically aligned when the "Show Me" button is present.
For example: https://svelte.dev/tutorial/adding-data
Before:
After:
> Fix misalignment of link text and icon

- sites/svelte.dev/src/routes/_components/Supporters/index.svelte
Prevents incorrectly sized items as seen in Safari
> Add limits to grid items

- sites/svelte.dev/src/routes/repl/[id]/index.json.js
#270 updated to the latest kit version and addressed breaking changes throughout the whole site, but @geoffrich must have overlooked this endpoint in the REPL.
Since saving REPLs is broken by this, I thought it would be fastest if I just straight into a PR.
Following the instructions to set up supabase and github oauth this works like a charm on localhost.
Much love <3 to all of you heroes working on the site
> Fix breaking change not handled for REPL endpoint

- sites/svelte.dev/README.md
- sites/svelte.dev/src/lib/db/client.js
- sites/svelte.dev/src/routes/repl/[id]/index.json.js
This is a followup to #273 and makes running the svelte.dev site locally a bit easier, for the benefit of folks who want to try out local copies of the compiler on saved REPLs (say, on one given as a repro for an open issue).
In dev mode, you are no longer required to set the `SUPABASE_` env vars, and attempting to load a REPL without them set will instead proxy the request to the production svelte.dev, similar to what happened in the old version of the Svelte site.
This also updates the readme for svelte.dev slightly with appropriate information.
> [chore] improve local REPL without local Supabase

- sites/svelte.dev/src/routes/faq/index.svelte
See https://github.com/sveltejs/kit/pull/3794#issuecomment-1033963412 for context
Remove custom code block styles on svelte.dev FAQ page, so that it matches the rest of the svelte sites.
> [docs] make FAQ code blocks match rest of site

- sites/svelte.dev/src/routes/faq/index.svelte
Followup to https://github.com/sveltejs/sites/pull/297
The code block CSS was not imported on the FAQ page, so the styles weren't applied when loading the page directly.
> Add syntax higlighting styles to FAQ

- packages/repl/src/lib/Output/srcdoc/index.html
Remove the horizontal padding of range input, that can lead to thinking that we can't reach the minimum value and maximum value.
Linked thread on Discord: https://discord.com/channels/457912077277855764/945764520654151800
> Remove horizontal padding of range input

- packages/repl/src/lib/Output/AstNode.svelte
There was a class called `toggle` in `src/lib/Output/AstNode.svelte`. And it was affected by the code below.
```css
/* sites/svelte.dev/src/routes/__layout.svelte */
:global(.toggle) {
bottom: var(--ukr-footer-height) !important;
}
```
I just changed the class name in `AstNode.svelte`.  Plz let me know if there is a preferred way to handle this. 
fix of  #317
> fix: Design of AST output

- packages/repl/package.json
i'm not quite sure what happened, but @bluwy suggested to add `"svelte"` entry to `@sveltejs/repl`
> fix build error with svelte-json-tree

- .npmrc
- package.json
- pnpm-lock.yaml
- sites/svelte.dev/src/routes/docs/index.svelte
- sites/svelte.dev/src/routes/examples/[slug]/index.svelte
- sites/svelte.dev/src/routes/examples/__layout.svelte
- sites/svelte.dev/src/routes/faq/index.svelte
- sites/svelte.dev/src/routes/tutorial/[slug]/index.svelte
- sites/svelte.dev/src/routes/tutorial/__layout.svelte
unfortunately `pnpm install` decided to update a lot of versions in the lockfile, notably kit itself made a sizable jump. Needs to be verified if thats ok.
regarding the filter change: 
https://pnpm.io/cli/publish#--filter-package_selector links to https://pnpm.io/filtering which shows --filter before the command
engine-strict and packageManager are helpers to ensure pnpm7 is used
> chore: update to pnpm7 and enforce using it

- sites/svelte.dev/src/routes/repl/[id]/index.svelte
In Safari, right clicking an element in the REPL preview and selecting "Inspect Element" would yield the wrong iframe as the target.
The correct iframe (.tab-content) has a class of .visible to display it, simple fix is to add `z-index: 1` to the declaration
> Fixes REPL targeting bug in Safari

- packages/site-kit/src/lib/docs/Main.svelte
The anchors in h4 are wrongly positioned, this is a small PR that fixes this problem by changing `display: block` to `display: inline`.
Here's a small comparison:
| svelte.dev  |  PR  |
| ------------------- | ------------------- |
|  ![image](https://user-images.githubusercontent.com/61414485/176435791-adb81b1c-5803-42cd-bc9d-ae9ae2449b2b.png) |  ![image](https://user-images.githubusercontent.com/61414485/176435872-89d5ba7f-8913-40c7-ba50-199f46ec9171.png) |
> Fix `h4` anchors positioning in `site-kit` package

- sites/svelte.dev/src/routes/index.svelte
The vite docs recommend the usage of npm create as a way to bootstrap via vite. Making this change to maintain consistency between vite docs and svelte quick start
> Changed the vite syntax to reflect vite docs.

- packages/repl/src/lib/SplitPane.svelte
i'm surprised we didn't get yelled at more for this. the REPL is kinda busted at the moment — Firefox doesn't know how big the container should be, and the `<SplitPane>` component keeps losing track of the mouse as soon as it touches the iframe:
https://user-images.githubusercontent.com/1162160/179646274-ba71e685-985e-4e12-81b2-6afdea92eb9d.mov
This fixes both.
> fix REPL pane resizing

- sites/svelte.dev/src/routes/index.svelte
Code example creates a directory named `myapp` but then tries to `cd` into `my-app`. Originally changed in 0cbac1aa4885d21d29b50ce607353e8f07103651.
> Fix incorrect directory name in code example

- sites/svelte.dev/src/hooks.server.js
- sites/svelte.dev/src/routes/blog/the-easiest-way-to-get-started/+page.js
- sites/svelte.dev/src/routes/roadmap/+page.js
Serve svelte.dev/roadmap so we can easily host it elsewhere in the future if we wish
The getting started page now lives at https://kit.svelte.dev/docs/introduction#getting-started
> setup redirects

- packages/site-kit/src/lib/components/NavItem.svelte
- packages/site-kit/src/lib/docs/Main.svelte
I'd like to make this a best practice for the following reasons:
- it makes it easier to use with tools like Vitest and Storybook
- it removes a circular dependency between `site-kit` and `kit.svelte.dev`
- it makes it possible to use the package on a non-SvelteKit site
- i'd guess that accessing `window.location.pathname` results in a slightly smaller compiler output than accessing `$app/stores`. you can't do this everywhere, but we can here in `onMount`
- I'm guessing it'd have the potential to make Rollup compilation faster though you might not notice unless you had a fairly large project and I'm not familiar enough with the Rollup internals to know if it works the way I imagine it might
> Decouple site-kit from SvelteKit

- packages/repl/jsconfig.json
- packages/repl/package.json
- packages/repl/src/app.html
- packages/repl/src/routes/+page.svelte
- packages/repl/svelte.config.js
- packages/repl/vite.config.js
updates the repl sveltekit app to work with the new routing system https://github.com/sveltejs/kit/discussions/5748 and new packaging command. https://github.com/sveltejs/kit/pull/5730
note: does not affect the actual library `packages/repl/src/lib`
> update repl package to work with latest sveltekit

- sites/svelte.dev/src/routes/blog/rss.xml/+server.js
closes #415. this was a victim of #413 — the RSS feed is now powered by the filesystem rather than an API, which means it needs to be prerendered. But that's a good thing, because regenerating it per request is silly
> prerender RSS feed

- sites/svelte.dev/content/blog/2023-02-01-whats-new-in-svelte-february-2023.md
Updated the PR title to better match intention. This is the first draft. Will update when it's a bit closer to the end of the month too :)
> blog: "What's new in Svelte" February newsletter

- pnpm-lock.yaml
- sites/hn.svelte.dev/package.json
- sites/svelte.dev/package.json
- sites/svelte.dev/vite.config.js
- pin repl version so we can freely adjust it in the meantime (it has incompatible style changes)
- make hn/svelte.dev packages private so we can't accidentally publish them
> pin site versions

- sites/svelte.dev/src/routes/+layout.svelte
This PR changes the Ukraine banner to a SvelteHack banner
- I removed some duplicated CSS that was there
- renamed all `ukr` CSS classes and custom props to just `banner`
- added three CSS custom props to make it easier to change the banner
> change Ukraine banner to SvelteHack banner

- packages/repl/package.json
- packages/repl/src/lib/workers/bundler/index.js
- pnpm-lock.yaml
Finally fixes #134.
Based on https://github.com/sveltejs/sites/issues/134#issuecomment-995449952 and https://github.com/sveltejs/sites/issues/134#issuecomment-1444393511.
~Still on draft since~ I don't know how to report the errors in importing to the user, see the two "TODO"s.
Related context: https://github.com/benmccann/esm-env/pull/2#issuecomment-1444437790
> feat: add support for `exports` field to REPL

- packages/repl/src/lib/Output/CompilerOptions.svelte
- packages/repl/src/lib/index.svelte
Svelte compiler changed css option to `'external' | 'injected' | 'none'` since 3.53. ([changelog](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3530))
This PR just updates the REPL UI to support the new option.
> add support for css option 'none'

- .changeset/proud-wombats-buy.md
- packages/repl/src/lib/Repl.svelte
- packages/repl/src/lib/types.d.ts
- packages/repl/src/routes/+page.svelte
When loading the files from a saved REPL renaming a file broke the REPL because selecting a new tab was storing the state from App.svelte for the newly selected file in the EDITOR_STATE_MAP. Given that the state includes the document itself after renaming the file the editor restored the state with the wrong doc.
See this REPL as an example, trying to rename ItemTypeOne substitute the content of ItemTypeOne.svelte with the one from App.svelte
https://svelte.dev/repl/d9d167fa8ded478ba4dea62257d75a10?version=3.8.0
> (fix) loading files from repl json broke the REPL upon renaming

- .changeset/fresh-days-know.md
- packages/repl/src/lib/Input/ComponentSelector.svelte
This fixes the automatic newline that get's added when renamig/creating a file
> (fix) avoid automatic newline when renaming/creating a file

- .changeset/sweet-pianos-sniff.md
- packages/repl/package.json
- packages/repl/src/lib/CodeMirror.svelte
- packages/repl/src/lib/Input/ModuleEditor.svelte
- packages/repl/src/lib/Repl.svelte
- packages/repl/src/lib/types.d.ts
- packages/repl/src/routes/+page.svelte
- pnpm-lock.yaml
closes #496
This issue is due to the fact that the array of the diagnostics get's out of sync with the actual code for a brief moment. This usually it's not a huge problem because it get's recomputed moments later but it can be a problem when the error falls outside of the max length of source code.
To avoid this issue i've added a bundling promise inside the context that get's reassigned whenever a bundling process starts and resolved immediately after the new bundle has been assigned to the store. The diagnostic has also been transformed from an array that get's recalculated dynamically to an async function that awaits the bundling process. Finally instead of simply passing the diagnostics to neocodemirror we create a `linter ` extension passing the aforementioned async function. …
> Fix attribute deletion

- .changeset/shy-bikes-prove.md
- packages/repl/src/lib/CodeMirror.svelte
- packages/repl/src/lib/Input/ModuleEditor.svelte
- packages/repl/src/routes/+page.svelte
Without this if there's a warning in a file different from the selected file the diagnostic inside codemirror will still show in the selected file. In the worst case this can lead to the whole repl crashing (if the current document is shorter than the warning position)
> (fix): show warnings only for the selected file in cm diagnostics

- pnpm-lock.yaml
- sites/hn.svelte.dev/jsconfig.json
- sites/hn.svelte.dev/package.json
- sites/hn.svelte.dev/src/app.html
- sites/hn.svelte.dev/src/global.d.ts
- sites/hn.svelte.dev/src/lib/Nav.svelte
- sites/hn.svelte.dev/src/routes/+error.svelte
- sites/hn.svelte.dev/src/routes/+page.js
- sites/hn.svelte.dev/src/routes/[list=category]/[page]/+page.js
- sites/hn.svelte.dev/src/routes/[list=category]/[page]/ItemSummary.svelte
- sites/hn.svelte.dev/src/routes/[list=category]/rss/+server.js
- sites/hn.svelte.dev/src/routes/item/[id]/+page.js
- sites/hn.svelte.dev/src/routes/item/[id]/Comment.svelte
- sites/hn.svelte.dev/src/routes/rss/+server.js
- sites/hn.svelte.dev/src/routes/user/[name]/+page.js
- sites/hn.svelte.dev/svelte.config.js
- sites/hn.svelte.dev/vite.config.js
- Updates deps of hn.svelte.dev
- Switches to using edge runtime for faster performance and less impact on environment
> feat(hn): update deps, edge based

- sites/hn.svelte.dev/src/app.html
As mentioned in discord, having so many non-svelte results show up when searching for svelte related content can negatively impact people's ability to find the content they are looking for
> Exclude HN site from search-engine indexing

- packages/repl/src/lib/Output/AstNode.svelte
This is a simple fix for the [issue#9205](https://github.com/sveltejs/svelte/issues/9205) I reported to Svelte.
> fix(repl): type indication for AstNode

- packages/repl/package.json
makes it easier to find your way here from npm
> chore: list repo info in repl's `package.json`

- pnpm-lock.yaml
- sites/hn.svelte.dev/package.json
- sites/hn.svelte.dev/src/app.css
- sites/hn.svelte.dev/src/app.d.ts
- sites/hn.svelte.dev/src/lib/Nav.svelte
- sites/hn.svelte.dev/src/lib/PreloadingIndicator.svelte
- sites/hn.svelte.dev/src/lib/ThemeToggler.svelte
- sites/hn.svelte.dev/src/routes/+layout.svelte
- sites/hn.svelte.dev/src/routes/[list=category]/[page]/+page.svelte
- sites/hn.svelte.dev/src/routes/[list=category]/[page]/ItemSummary.svelte
- sites/hn.svelte.dev/src/routes/item/[id]/+page.svelte
- sites/hn.svelte.dev/src/routes/item/[id]/Comment.svelte
- sites/hn.svelte.dev/src/routes/user/[name]/+page.svelte
- sites/hn.svelte.dev/svelte.config.js
Upgrades all other dependencies as well. TypeScript was added as one because it seems that types aren't generated inside `.svelte-kit` otherwise?
> feat(hn): Svelte 5

- sites/hn.svelte.dev/src/routes/about/+page.js
Allows for preloading to work on the about page.
> fix(hn): enable CSR on about page and prerender it
