sites/kit.svelte.dev/src/lib/generate_docs.js
sites/kit.svelte.dev/src/routes/$layout.svelte
sites/kit.svelte.dev/src/routes/faq/index.json.js
sites/kit.svelte.dev/src/routes/faq/index.svelte

Add nav bar link and a section styled similarly to that of Sapper incuding section links

Add an FAQ section to the docs

---

.github/workflows/docs-deploy-trigger.yml

https://github.com/sveltejs/sites/runs/2371293908?check_suite_focus=true

chore: add additional inputs to deploy docs workflow

---

packages/site-kit/components/Hero.svelte
packages/site-kit/components/Nav.svelte
sites/kit.svelte.dev/src/routes/$layout.svelte
sites/kit.svelte.dev/src/routes/docs/index.svelte
sites/kit.svelte.dev/src/routes/faq/index.svelte
sites/kit.svelte.dev/src/routes/index.svelte
sites/kit.svelte.dev/src/routes/migrating/index.svelte

Fixes a handful of items identified by Lighthouse

Lighthouse

---

packages/site-kit/base.css
packages/site-kit/components/GuideContents.svelte

Fixes #43
This ports @peopledrivemecrazy's PR for the same changes in the old site-kit repo (https://github.com/sveltejs/site-kit/pull/32).

Make links copyable in docs

---

sites/svelte.dev/src/routes/blog/[slug].svelte

import code.css on blog pages

---

pnpm-lock.yaml

pnpm does this automatically when I run `pnpm install`

[chore] update lockfile

---

packages/repl/src/lib/workers/bundler/index.js

https://github.com/sveltejs/svelte-repl/pull/145

only import from local file if importer is local

---

packages/repl/src/lib/index.svelte

https://github.com/sveltejs/svelte-repl/pull/151

remove some unused code

---

.vscode/extensions.json
.vscode/settings.json

we decided against including this stuff by default

remove .vscode stuff

---

packages/repl/src/lib/Output/Viewer.svelte

https://github.com/sveltejs/svelte-repl/pull/132
want to test this one before merging, check it doesn't have any odd side-effects

change execution order

---

packages/repl/src/lib/CodeMirror.svelte
packages/repl/src/lib/Output/index.svelte

adds the fixes from https://github.com/sveltejs/svelte-repl/pull/168, plus a couple of adjacent tidy-ups

implement a11y fixes from svelte-repl

---

packages/repl/src/lib/index.js
packages/repl/svelte.config.js

not a big deal, but makes things a bit tidier

only expose <Repl> from repl package

---

packages/repl/src/lib/workers/bundler/index.js
packages/repl/src/lib/workers/bundler/plugins/replace.js

https://github.com/sveltejs/svelte-repl/pull/106

add replace plugin

---

packages/repl/src/lib/Input/ComponentSelector.svelte
packages/repl/src/lib/index.svelte
sites/svelte.dev/src/routes/repl/[id]/index.svelte

only show modified and prevent leaving for repl url

---

sites/svelte.dev/src/routes/repl/[id]/index.json.js

@benmccann probably a typo here

fix repl gist owner = undefined

---

packages/repl/src/lib/workers/bundler/plugins/commonjs.js

update acorn worker parser version to ecma 12

---

sites/svelte.dev/src/lib/db/types.d.ts
sites/svelte.dev/src/routes/repl/[id]/_components/AppControls/index.svelte
sites/svelte.dev/src/routes/repl/[id]/index.json.js

fix saving

---

packages/site-kit/components/docs/Main.svelte

fix disappearing h4s

---

sites/svelte.dev/src/routes/_components/WhosUsingSvelte/index.svelte

what an absolute fucking joke of a browser

fix missing/glitching images on safari

---

db/setup.sql
sites/svelte.dev/src/lib/db/gist.js

Fixes #191 — will just need to create the `gist_list` function on the prod db

sort repls by both updated_at and created_at

---

db/setup.sql
sites/svelte.dev/src/lib/db/gist.js

we decided against actually deleting gists, when we do eventually get round to exposing the ability via the UI. will need to update the prod db before merging this
* add `deleted_at timestamptz` column to `gist`
* update functions

update deleted_at column rather than actually deleting

---

packages/site-kit/src/lib/components/Icons.svelte

update delete icon

---

sites/svelte.dev/src/routes/apps/index.svelte

Makes checkboxes easier to hit on mobile

expand hit area, add aria-label

---

sites/svelte.dev/src/routes/tutorial/[slug]/index.svelte

fix tutorial edit links

---

sites/svelte.dev/src/routes/repl/[id]/index.svelte

alternative to #187 — fetches the gist data in `load`, rather than getting it later. means the data can be used for twitter cards (#100), and is prefetchable, and we don't see `Loading...` any more.

fetch gist in load

---

sites/svelte.dev/src/routes/examples/[slug]/_TableOfContents.svelte

Fixes the first issue mentioned in #229.

[fix] links from examples to REPLs

---

package.json
pnpm-lock.yaml

This resolves #230 for me - I'm now able to install dependencies. We'll see whether this breaks the preview deployment. If other folks aren't comfortable with this change, that's understandable, but it would certainly hamper my ability to contribute to this repo.

[fix] force sharp@^0.29.0

---

packages/site-kit/src/lib/base.css

fix blockquote ul font-size

---

db/README.md

Some updates after setting up Supabase myself. And avoiding the need for `psql` too.

update db setup docs

---

sites/kit.svelte.dev/src/routes/faq/index.svelte
sites/svelte.dev/src/routes/__layout.svelte
sites/svelte.dev/src/routes/blog/index.svelte

Totally forgot about this branch I pushed
Fixes #249

absolute remaining links

---

sites/svelte.dev/.env.example
sites/svelte.dev/README.md
sites/svelte.dev/src/routes/repl/local/[...path].js

Update docs and `repl/local` to work with a local copy of Svelte.

update local svelte setup

---

packages/site-kit/src/lib/components/Nav.svelte

this was causing issues with the search box, and is apparently not needed

remove z-index on nav ul

---

packages/repl/package.json
packages/repl/src/lib/Output/Console.svelte
pnpm-lock.yaml

this fixes some styling issues, eg when logging `new Map()`
before:
after:

feat: update svelte-json-tree

---

packages/site-kit/src/lib/base.css
packages/site-kit/src/lib/docs/Contents.svelte

Let us never speak of this again

Increase the text contrast in the sidebar

---

sites/svelte.dev/src/routes/tutorial/api/album.js

creating our own api in the svelte.dev to replace the `jsonplaceholder.typicode.com` api used in the tutorial
related: https://github.com/sveltejs/svelte/issues/6233

album api to replace jsonplaceholder.typicode.com

---

sites/hn.svelte.dev/src/lib/ThemeToggler.svelte

Fix [#336](https://github.com/sveltejs/sites/issues/336)

fix: hn theme toggler

---

sites/svelte.dev/src/lib/db/gist.js
sites/svelte.dev/src/routes/(authed)/repl/[id].json/+server.js

Ref https://github.com/sveltejs/sites/issues/399

Fix REPL 404 handling

---

pnpm-lock.yaml
sites/svelte.dev/package.json
sites/svelte.dev/src/lib/db/client.js

migration guide here: https://supabase.com/blog/supabase-js-v2

upgrade supabase client

---

sites/svelte.dev/src/routes/(authed)/repl/[id].json/+server.js
sites/svelte.dev/src/routes/+error.svelte

fixes https://github.com/sveltejs/sites/issues/399

Validate that ID is UUID before hitting Supabase

---

db/README.md
sites/svelte.dev/README.md
sites/svelte.dev/src/routes/(authed)/repl/[id].json/+server.js
sites/svelte.dev/src/routes/auth/login/+server.js

[rendered](https://github.com/sveltejs/sites/blob/no-minify/sites/svelte.dev/README.md)

Fix saving in REPL. Update local setup instructions

---

sites/svelte.dev/content/blog/2022-12-14-announcing-sveltekit-1.0.md

Not sure if intentional to have it as 587 when the final pre-release is 589.

chore(blog): change final pre-release to 589

---

sites/svelte.dev/content/blog/2020-10-01-whats-new-in-svelte-october-2020.md
sites/svelte.dev/content/blog/2020-11-01-whats-new-in-svelte-november-2020.md
sites/svelte.dev/content/blog/2020-12-01-whats-new-in-svelte-december-2020.md
sites/svelte.dev/content/blog/2021-01-01-whats-new-in-svelte-january-2021.md
sites/svelte.dev/content/blog/2021-02-01-whats-new-in-svelte-february-2021.md
sites/svelte.dev/content/blog/2021-03-01-whats-new-in-svelte-march-2021.md
sites/svelte.dev/content/blog/2021-04-01-whats-new-in-svelte-april-2021.md
sites/svelte.dev/content/blog/2021-05-01-whats-new-in-svelte-may-2021.md
sites/svelte.dev/content/blog/2021-06-01-whats-new-in-svelte-june-2021.md
sites/svelte.dev/content/blog/2021-07-01-whats-new-in-svelte-july-2021.md
sites/svelte.dev/content/blog/2021-08-01-whats-new-in-svelte-august-2021.md
sites/svelte.dev/content/blog/2021-09-01-whats-new-in-svelte-september-2021.md
sites/svelte.dev/content/blog/2021-10-01-whats-new-in-svelte-october-2021.md
sites/svelte.dev/content/blog/2021-11-01-whats-new-in-svelte-november-2021.md
sites/svelte.dev/content/blog/2021-12-01-whats-new-in-svelte-december-2021.md
sites/svelte.dev/content/blog/2022-01-01-whats-new-in-svelte-january-2022.md
sites/svelte.dev/content/blog/2022-02-01-whats-new-in-svelte-february-2022.md
sites/svelte.dev/content/blog/2022-03-01-whats-new-in-svelte-march-2022.md
sites/svelte.dev/content/blog/2022-04-01-whats-new-in-svelte-april-2022.md
sites/svelte.dev/content/blog/2022-05-01-whats-new-in-svelte-may-2022.md
sites/svelte.dev/content/blog/2022-06-01-whats-new-in-svelte-june-2022.md
sites/svelte.dev/content/blog/2022-07-01-whats-new-in-svelte-july-2022.md
sites/svelte.dev/content/blog/2022-08-01-whats-new-in-svelte-august-2022.md
sites/svelte.dev/content/blog/2022-09-01-whats-new-in-svelte-september-2022.md
sites/svelte.dev/content/blog/2022-10-01-whats-new-in-svelte-october-2022.md
sites/svelte.dev/content/blog/2022-11-01-whats-new-in-svelte-november-2022.md
sites/svelte.dev/content/blog/2022-12-01-whats-new-in-svelte-december-2022.md

I've been going by Dani for a while now... it's about time I update my presence on the blog to reflect that.
Feel free to comment here or DM on discord if you have any questions!
Will update #419 to reflect this change once this PR is approved

[meta] update name and website for Dani to match current name

---

sites/svelte.dev/content/blog/2023-01-01-whats-new-in-svelte-january-2023.md

Let me know if there's anything I missed!

[docs] "What's new in Svelte" January newsletter 

---

sites/svelte.dev/src/lib/utils/examples.js
sites/svelte.dev/src/routes/(authed)/repl/[id].json/+server.js

There should probably be better validation instead of allowing arbitrary json through the API
<details><summary>spoiler</summary>but probably a TODO for the new site instead of this one.</details>

fix repl breaking when empty files are saved

---

.github/workflows/release.yml
pnpm-lock.yaml
sites/hn.svelte.dev/package.json

... and updates HN app to kit@1.5.0 to avoid build error

feat: Add changesets

---

.changeset/dull-news-count.md
packages/repl/package.json
pnpm-lock.yaml

fix(repl): Fix publish directory

---

sites/svelte.dev/content/blog/2023-03-01-whats-new-in-svelte-march-2023.md

Let me know if I missed anything!

blog: "What's new in Svelte" March newsletter

---

sites/svelte.dev/src/routes/+layout.svelte

add x button to close SvelteHack banner and remove old comment for the Ukraine banner that I forgot to delete last time

add x button to close SvelteHack banner

---

sites/svelte.dev/content/blog/2023-04-01-whats-new-in-svelte-april-2023.md

Let me know if I missed anything!

blog: "What's new in Svelte" April newsletter

---

.changeset/quiet-garlics-tickle.md
package.json
packages/repl/.gitignore
packages/repl/package.json
packages/repl/src/lib/Output/Viewer.svelte
packages/repl/src/lib/workers/bundler/index.js
packages/repl/svelte.config.js
pnpm-lock.yaml

Should not depend on SvelteKit or Vite anymore
svelte-package is updated
No breaking changes

feat(repl): Make SvelteKit agnostic

---

sites/svelte.dev/content/blog/2023-05-01-whats-new-in-svelte-may-2023.md

I was thinking we could mention the hackathon winner in the intro

blog: "What's new in Svelte" May newsletter

---

sites/svelte.dev/src/routes/+layout.svelte

Change Banner to point to Svelte Summit

---

.changeset/fresh-countries-hear.md
packages/repl/package.json
packages/repl/src/lib/Input/ModuleEditor.svelte
packages/repl/src/lib/Repl.svelte
packages/repl/src/lib/types.d.ts
packages/repl/src/lib/workers/bundler/plugins/commonjs.js
packages/repl/src/lib/workers/bundler/plugins/glsl.js
packages/repl/src/lib/workers/bundler/plugins/json.js
packages/repl/src/lib/workers/bundler/plugins/replace.js
pnpm-lock.yaml

fix(repl): Minor fixes

---

sites/svelte.dev/src/routes/+layout.svelte

Removes the banner and any related CSS and JavaScript.
(I somehow screwed this up twice :grimacing:)

site: remove banner

---

sites/svelte.dev/content/blog/2023-06-01-whats-new-in-svelte-june-2023.md

Sorry it's a bit last minute, this month! Let me know if I missed anything.

blog: "What's new in Svelte" June newsletter

---

.changeset/pink-maps-guess.md
packages/repl/package.json
packages/repl/src/lib/CodeMirror.svelte
packages/repl/vite.config.js
pnpm-lock.yaml

This fixes the attribute deletion causing freeze error

chore(repl): Update neocodemirror to 0.0.14

---

.changeset/clever-pumas-fly.md
packages/repl/package.json
packages/repl/src/lib/Output/Viewer.svelte
packages/repl/src/lib/Output/console/Console.svelte
packages/repl/src/lib/Output/console/ConsoleLine.svelte
pnpm-lock.yaml

feat(repl): allow dark mode for svelte-json-tree

---

sites/hn.svelte.dev/src/routes/item/[id]/Comment.svelte

This drops javascript requirement while toggles between show/hide on comments.

feat(hn): toggle comments by details > summary

---

sites/hn.svelte.dev/src/routes/+error.svelte

HN example contains an unused import, this pull request removes it

Update +error.svelte in HN example to remove unused import
